# Generated by Django 3.2.13 on 2022-06-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_move_member_and_librarian_from_core'),
        ('core', '0005_add_staff_code_to_librarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.DeleteModel(
            name='Librarian',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
