# Generated by Django 3.2.13 on 2022-06-05 15:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0009_remove_borrowedbook'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('book_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.bookitem')),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
        ),
    ]
