# Generated by Django 3.2.13 on 2022-06-06 15:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('library', '0010_alter_bookitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField(auto_now_add=True)),
                ('due_time', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)])),
                ('book_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.bookitem')),
                ('reserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member')),
            ],
        ),
    ]
